### ISSUE TITLE
DOA using SRP for recorded data.

### ISSUE THREAD

**Issue by aabs7** [LCAV/pyroomacoustics#111]
I am doing DOA with SRP and I am confused about how to provide input signal for real time implementation of DOA.
I've placed my microhphones as shown below:
![microphone](https://user-images.githubusercontent.com/25321415/60017069-a563d980-96a7-11e9-92e5-bd0419fceec5.jpg)
where I've used **Mic1** as refrence and hence *mic1 = np.array([0,0])* and distance between two adjacent microphones is ***10cm***.(*although in code there it is written in cm, it is now converted to metres*)
My code is as:
![SRP](https://user-images.githubusercontent.com/25321415/60017301-2327e500-96a8-11e9-8f92-eff2bb9bb6c1.jpg)

My question is- Is my implementation correct? Because output is not showing correctly.

**Comment by fakufaku** [comment]
Hi @aabs7 , nice array 😄 . As far as I can tell the implementation looks correct (you pulled it from the example right ?). When dealing with real arrays, the first thing I would do is check that the assignment of microphone locations (created here by `circular_2D_array`) to channels is correct. If the mapping is not correct, you will get garbage output.

For example, if you use two I2S bus to connect your microphones, you might have something like:
```
mic1 -> I2S1 L
mic2 -> I2S1 R
mic3 -> I2S2 L
mic4 -> I2S2 R
```
And you would expect that the channels you get are ordered like this:
```
[I2S1 L, I2S1 R, I2S2 L, I2S2 R]
```
but often (in Linux for example), left channels and right channels are grouped, so that you have
```
[ I2S1 L, I2S2 L, I2S1 R, I2S2 R]
```

On way of finding out the order is to make a recording where you gently tap on each microphone one after the other. Then in the recorded file you check in which order the tap is recorded in the channels.

PS. It is usually considered better practice to copy paste your code in text rather than using screenshot. It makes it easier to test your code for example.

**Comment by fakufaku** [comment]
Closed for lack of activity.
