### ISSUE TITLE
Directional vs Omni Directional Source

### ISSUE THREAD

**Issue by rocco-haro** [LCAV/pyroomacoustics#131]
After viewing the soundsource.py, I don't think this is possible, but I was wondering if there is any advice/guidance you may give me so that I can provide this functionality to the pyroomacoustics repository. 

I'd like to create a sound source that behaves like: https://www.youtube.com/watch?v=DVp2PsSj1vI and simulate it. 

How do you suggest I proceed with accomplishing this? With your guidance, i'd be happy to contribute to this awesome project. 

Kind regards.

**Comment by fakufaku** [comment]
Hi @rocco-haro, directional sources are indeed not supported at this time. It would indeed be nice to support them. I have been thinking about this for a while and pretty much know how this could be done, but haven't got around doing it.

For background, I should mention that we are working on an improvement of the simulator with a hybrid image source model/ray tracing simulator in the `next_gen_simulator` branch.

In ray tracing, the implementation is pretty straightforward since we can just adjust the number of particles thrown to fit any directional pattern. For the image source model, things are a little bit more trickly.

Let us start from the basics. There are 

Directivity Patterns for Sources in the ISM
-------------------------------------------

The image source model (ISM) works by tracing a sound "ray" exactly from source to microphone. This is done by assuming all walls are perfect reflectors.

For cuboid rooms (aka shoebox), the procedure is pretty straightforward.
One just assume that there is a grid of reflections of the room along the different walls. Then the position of the reflected source is easily computed from the orders of reflections wrt the different walls and wehter they are odd/even. From the position of the source. Similarly, the angular position of the microphone with respect to the reflected source could be determined and used to apply a weighing to the reflection in the impulse response.

For arbitrary polyhedral rooms, the algorithm is more complicated but can be implemented recursively, as described in the original paper.

> J. Borish, “Extension of the image model to arbitrary polyhedra,” J. Acoust. Soc. Am., vol. 75, no. 6, pp. 1827–1836, 1984.

In this case, the angle between the source and the microphone can be computed at the end of the recursion.

Directivity Patterns for Sources in Ray Tracing
-----------------------------------------------

This case is fairly straightforward. Since the simulation relies on launching a large number of particles from the sources, the distribution of particles can be modified to fit the directivity of the source.

Setting the Directivity Patterns
--------------------------------

For the implementation in the package, a critical part to think about is the user interface.

* How should directivity patterns be represented ? Analytical vs discrite representations ?
* How should the user define the rotation of the sound source (Euler angles ?)

Suggestion for Initial Development
----------------------------------

As a start, I would suggest to focus on

* ISM for shoebox rooms
* Analytical directivity patterns, e.g., cardioid
* Implement a hierarchy of classes for directional sources, with the base (default) being the omnidirectional source.

Please let me know if this makes sense, and how I could further helps.

**Comment by rocco-haro** [comment]
@fakufaku  Thanks for this write up. I'm sad to say that much of this has gone way over my head! Do you have any suggested readings ? My background is just a B.S. in Computer Science. I'd like to contribute, but I don't understand much of the maths. I'll read the source code to see if that can help

**Comment by fakufaku** [comment]
There should be no super hard math involved, but there is quite a bit of background involved. One starting point could be the paper from Borish mentioned above. For the ray tracing simulator, a concrete way of contributing would be to provide algorithms that produce samples on the sphere corresponding to source directivity patterns. I understand this might still sound abstract, so I'll try to come back with more concrete suggestions.

**Comment by fakufaku** [comment]
We have started implementation of directivities! Basic ones are available for source and microphones in the shoebox image source model! 🎉
