### ISSUE TITLE
Question about delays introduced by the simulation

### ISSUE THREAD

**Issue by yujiacheng333** [LCAV/pyroomacoustics#136]
Hellow, I'd like to make multi-channel source separation by deep learning. It's an easy way that use pyroomacoustics. However I found taht the length of raw audio signal's length is diffirent to mac_array return. So, how can I obtain labesl of multichannel?  Thx for your help, and thx for pyroomacoustics.

**Comment by fakufaku** [comment]
Hi @yujiacheng333 , sorry for the belated reply.

The length is indeed different due to the filtering by the room impulse response. The delay can be broken down in two parts:
* 40 samples are an artifact from the simulation. The Thus, the first 40 samples can be dropped.
* Other delays are due to sound propagation in the room and need to be taken into account by your algorithm. I would suggest that you add an alignment step somewhere to align the groundtruth signals to the simulated signals. Generalized cross-correlation (GCC-PHAT) is a popular method to find the offset.

**Comment by yujiacheng333** [comment]
Ok,thanks for your help~~pyroomacoustics best!!
