### ISSUE TITLE
Updating source signal without recomputing RIR ?

### ISSUE THREAD

**Issue by hbredin** [LCAV/pyroomacoustics#152]
I'd like to use pyroomacoustics for on-the-fly data augmentation in [pyannote.audio](https://github.com/pyannote/pyannote-audio).

I already have a working version [here](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/augmentation/reverb.py) that does the following:
- [generate a room with random dimension](https://github.com/pyannote/pyannote-audio/blob/799acf2da293283588b1fdd177d74a9c4b04e78a/pyannote/audio/augmentation/reverb.py#L100-L108)
- [add two sources at random positions in this room](https://github.com/pyannote/pyannote-audio/blob/799acf2da293283588b1fdd177d74a9c4b04e78a/pyannote/audio/augmentation/reverb.py#L110-L130)
- [place one microphone at a random position in this room](https://github.com/pyannote/pyannote-audio/blob/799acf2da293283588b1fdd177d74a9c4b04e78a/pyannote/audio/augmentation/reverb.py#L132-L137) 
- compute RIR
- simulate room
- return the microphone signal

It works as expected (thanks for the great tool by the way!) but computing RIR is obviously the part that takes most of the computation time (especially since I am doing this for every new pair of signals).  

To speed things up, I would like to re-use the RIR for different pairs of signals, keeping the same room shape, the same sources positions, the same microphone position, but updating the source signals. 

Does it even make sense? Or does the RIR computed with `room.compute_rir()` depend on the actual content of the signals (my understanding is that it does not but I am new to this so might be wrong).

If this does make sense, what is the correct way of updating the signal without changing anything else about the source? Is there something like `room.update_source_signal(new_signal)` that I could then use like that:

```python
room = ...
room.add_source(..., signal=signal1, ...)
room.add_source(..., signal=signal2, ...)
microphone = room.add_microphone_array(...)
room.compute_rir()
room.simulate()
# do something with room.mic_array.signals
room.update_source_signal(new_signal1, new_signal2)
# notice we do not need to call room.compute_rir() again
room.simulate()
# do something with room.mic_array.signals
```

**Comment by fakufaku** [comment]
Hi, what you're doing sounds very interesting. You are completely right that the room impulse response (RIR) computation does not depend on the signal content. The simulation will produce a fixed FIR filter with which the signal is convolved. The easiest way to reuse the simulation is to just save the FIR filter taps and convolve a different signal.

After the call to `room.compute_rir()`, all the filters are stored in `room.rir`, which is a list of lists. You can access the RIR between the `m`th microphone and `s`th source like this: `room.rir[m][s]`. The filter itself is a numpy array.

In fact the `room.simulate()` is just synctactic sugar around `scipy.signal.fftconvolve`, so you can just skip it and call `fftconvolve` directly on several different signals.

Maybe one more thing to take into account is the scale of the filters. Due to propagation, the amplitude of the signal is much smaller (i.e. the taps of the filter are usually quite small). However, microphones typically have a gain to bring back the signal in a reasonable range (e.g. [-1, 1]). It is thus reasonable to rescale all the output signals by a fixed factor, in case you care about that. If you decide to do that, though, you should be careful to scale all the microphone signals in the *same* simulation by the same amount, so that the relative amplitudes are correct.

**Comment by hbredin** [comment]
Thanks for the detailed answer, that is very helpful. 

I am now able to re-use a fixed set of RIRs, that is updated once in a while. 
It does make things much faster.

However, it is still too slow for my use case. 
I'll have to look for ways to make `fftconvolve` (the main bottleneck) faster. 

Closing this issue anyway because my initial answer was solved (but I would be happy to hear about faster `fftconvolve` implementations if you happen to know one :-))

**Comment by fakufaku** [comment]
Happy that helped. `fftconvolve` is already an efficient implementation of convolution with the fft. You might indeed look at gpu options to make it faster. I am not sure how much parallelized it is in scipy, so possibly, you could also use multiprocessing to run `fftconvolve` on multiple signals at a time.

One more point is that currently pyroomacoustics makes RIR a little longer than they strictly need to be. It is currently accepted that they don't need to be longer than the `T60`, that is the time it takes for the RIR to fall 60 dB from its maximum value. The function `pyroomacoustics.experimental.measure_rt60` measures the `T60` of an RIR. You could use to shorten the RIR to this length. Be mindful that the `T60` is computed from the maximum, so you should cut the signal at `T_max + T60`.

**Comment by hbredin** [comment]
> Happy that helped. `fftconvolve` is already an efficient implementation of convolution with the fft. You might indeed look at gpu options to make it faster. I am not sure how much parallelized it is in scipy, so possibly, you could also use multiprocessing to run `fftconvolve` on multiple signals at a time.

Looking at CPU load, I can tell that `scipy`'s `fftconvolve` is already heavily parallelized so multiprocessing is not helping: I tried and it actually makes things even slightly slower in my use case.

> One more point is that currently pyroomacoustics makes RIR a little longer than they strictly need to be. It is currently accepted that they don't need to be longer than the `T60`, that is the time it takes for the RIR to fall 60 dB from its maximum value. The function `pyroomacoustics.experimental.measure_rt60` measures the `T60` of an RIR. You could use to shorten the RIR to this length. Be mindful that the `T60` is computed from the maximum, so you should cut the signal at `T_max + T60`.

Thanks. I'll first try the GPU thing and fallback to this if/when I fail.
