### ISSUE TITLE
Cannot open include file: 'Eigen/Core': No such file or directory

### ISSUE THREAD

**Issue by ludlows** [LCAV/pyroomacoustics#174]
C:\Users\lu\AppData\Local\Temp\pip-build-env-e7fgrsfc\overlay\Lib\site-packages\pybind11\include\pybind11/eigen.h(36): fatal error C1083: Cannot open include file: 'Eigen/Core': No such file or directory
  C:\Users\lu\AppData\Local\Temp\pip-build-env-e7fgrsfc\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\lu\AppData\Local\Temp\pip-req-build-g6c5etpp\pyroomacoustics\build_rir.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pyroomacoustics
Failed to build pyroomacoustics
ERROR: Could not build wheels for pyroomacoustics which use PEP 517 and cannot be installed directly

----------------------------------------------------------------------------------------------------- 

The above messages show that the installing procedure cannot find 'Eigen/Core'. 
I am using Python3.7 and numpy1.18.

**Comment by fakufaku** [comment]
Hi, thanks for letting us know! It looks like you need to initialize the repository submodules. I haven't run the command, but I think that something like the following (or a variant) should get you starterd.
```
git submodule update --init pyroomacoustics/libroom_src/ext/eigen
```
You can also refer to local development instructions [here](https://github.com/LCAV/pyroomacoustics/blob/master/CONTRIBUTING.rst#develop-locally). Please let us know if you run into more problems so that we can improve the instructions.

**Comment by ludlows** [comment]
thanks for your suggestions. 
the problem has been solved.
