### ISSUE TITLE
Reverberation time

### ISSUE THREAD

**Issue by maelp** [LCAV/pyroomacoustics#18]
Is there a simple way to convert between a reverberation time in T60 and an absorption coefficient?

This paper mentions the Eyring's empirical equation to convert to a reflection coefficient which I assume is (1 - absorption), is it something which is often used?

https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46107.pdf

**Comment by fakufaku** [comment]
Hi @maelp , I don't know if you still need it, but you might give a go to [Sabine's formula](https://en.wikipedia.org/wiki/Reverberation#Sabine_equation). I was thinking myself that it would actually be nice to give an RT60 parameter rather than straight absorption coefficient when creating the room. Let's keep this issue open for now.

**Comment by fakufaku** [comment]
Somewhat addressed by the addition of [inverse Sabine function](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.acoustics.html#pyroomacoustics.acoustics.inverse_sabine) in the latest version 0.4.0.
