### ISSUE TITLE
ValueError: The source must be added inside the room.

### ISSUE THREAD

**Issue by seacj** [LCAV/pyroomacoustics#181]
Here's the code. 
1. The source is inside the room.
2. In a strange way， sometimes the code works, but sometimes it doesn't.  So I reproduce it in a loop. The result is shown in the image below. By the way, the parameters are randomly generated. 

```
def makeroom(depth,width,height,d,w,h):
    room = pra.ShoeBox([depth, width, height],
                           fs=16000)
    source = [d,w,h]
    room.add_source(source,
                        signal=signal,
                        delay=0.)

for i in range(100000):
    if i%100 == 0:
        print(i)
    makeroom(6.468126354128832,6.0990278272355924,7.635956066742525,5.504990795762074,6.097878947965448,1.4603047873893646)
```

![image](https://user-images.githubusercontent.com/19593898/89105118-02a48f80-d451-11ea-89dc-656d3fc4e5be.png)

**Comment by fakufaku** [comment]
@seacj , thanks for reporting this. The problem here is that the `y` coordinate is *very* close to the wall (~1.2 mm). The code for the geometry (intersection with walls, etc) works up to an `epsilon`, i.e. intersection is declared if it is within `1e-4` from a wall. In this case, this tolerance was a little too large. I can fix the problem by setting the tolerance a little lower. I merge the fix in an upcoming version.
This being said, it is probably better to avoid using sources/microphones too close to the wall. Not only due to the geometry computation consideration, but also because the simulator approximates acoustics less well in that situation.

**Comment by seacj** [comment]
solved

**Comment by DanTremonti** [comment]
Hi @fakufaku, if I understand correctly, the modified value of epsilon will allow closer placement of sources with the room boundaries, but is not applicable in the `Room.is_inside()` check.
If that's the case, wouldn't it be helpful if the epsilon distance is also considered in the check - `Room.is_inside()`?

In my case I generate a random coordinate for placing a source, and use the `is_inside()` check to validate the generated coordinate. But this fails with the error - `ValueError: The source must be added inside the room.`, which happens while adding the source to the room.

Sorry I haven't checked your implementation, as I'm not proficient with C code.
