### ISSUE TITLE
Question: Blind Source Seperation best for 2 channel

### ISSUE THREAD

**Issue by StuartIanNaylor** [LCAV/pyroomacoustics#213]
Hi wondering if you could point a BSS noob in the right direction.

Is there a BSS method specifically for speech that can work on 2 channels where the better signal channel is known, that could be adapted for realtime processing?

AuxIVA
Trinicon
ILRMA
SparseAuxIVA
FastMNMF

Are the choices but without prior knowledge does the above represent an evolution of methods or are they specific to situations and would anyone maybe have a punt at giving a brief review?
I am aiming for low load 2 channel separation (2 mic) if at all possible?

**Comment by fakufaku** [comment]
Hi @StuartIanNaylor 
It depends on your application. If you know that one of the channels is (significantly) better, you might be looking at a case where what you want is rather noise cancelling, which can be done with the [LMS algorithm](https://en.wikipedia.org/wiki/Least_mean_squares_filter). There are some adaptive filtering algorithms in pyroomacoustics too [here](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.adaptive.html).
Now, if you would rather use BSS, I would recommend to go with AuxIVA and see if it works for you. The other methods are more advanced and may be more difficult to use effectively.

PS. I close the issue because it is not related to pyroomacoustics directly, but feel free to respond regardless.
