### ISSUE TITLE
Incorrect algorithm of projection back?

### ISSUE THREAD

**Issue by tky823** [LCAV/pyroomacoustics#223]
Thanks for the nice repo!

I have a question about projection back. Let me denote `m`: reference channel (fixed), `n`: source index, `j`: time frame. I omit the frequency bin index. The mixing system is

<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}x_{mj}=\sum_{n=1}^{N}a^{*}_{mn}y_{nj}...(1)\end{align*}">

where `x` and `y` are the mixed and separated signal, respectively. `a` is mixing coefficient.
In this repo, the separated signal after projection back is given by

<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}\hat{y}_{nj}=z^{*}_{mn}y_{nj}\end{align*}">

where

<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}z_{mn}=\frac{\sum_{j}x_{mj}^{*}y_{nj}}{\sum_{j}y_{nj}^{*}y_{nj}}...(2)\end{align*}">

However, in my understanding, projection back is defined as follows

<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}\hat{y}_{nj}=a^{*}_{mn}y_{nj}\end{align*}">

We can calculate `a` from `x` and `y`.

Is the current implementation of this repo correct?

**Comment by tky823** [comment]
Substituting eq. (1) into (2), 
<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}z_{mn}=\frac{\sum_{l}a_{ml}\sum_{j}y_{lj}^{*}y_{nj}}{\sum_{j}y_{nj}^{*}y_{nj}}...(2)\end{align*}">
If
<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}\frac{1}{J}\sum_{j}y_{lj}^{*}y_{nj}=\lambda_{n}\delta_{nl}=\begin{cases}\lambda_{n}(\rm{if}l=n)\\0(\rm{otherwise})\end{cases}\end{align*}">
(statistically independent between separated sources), this implementation is same as original projection back.
<img src="https://render.githubusercontent.com/render/math?math=\begin{align*}z_{mn}=a_{mn}\end{align*}">

**Comment by fakufaku** [comment]
Hi @tky823 ,  from your question, I am not completely clear about what you think the problem is.

As far as I know, there are two techniques to adjust the scale and phase of the output of BSS:

* projection back (PB)
* minimum distortion principle (MDP)

This is where things get confusing... :) Although the function is called `proj_back` in pyroomacoustics, it implements MDP.

In MDP, we adjust the scale by finding the filter that minimizes the distance to one of the microphones,
<img src="https://render.githubusercontent.com/render/math?math=\underset{z}{\min}\ \mathbb{E}[| z y_{nj} - x_{mj}|^2]">
Solving for `z` gives equation (2) in your post.
The advantage of MDP is that it can be also used in beamforming when the full demixing matrix is not know/computed.

Now, PB is a little bit different. PB takes advantage of the linear relation ship between the demixed sources and the input signal:
<img src="https://render.githubusercontent.com/render/math?math=\mathbf{x} = \mathbf{A} \mathbf{y}">
Now we can replace all but one of the sources by zeros in the source vector `y` and obtain the contribution of that source only at microphones:
<img src="https://render.githubusercontent.com/render/math?math=\hat{\mathbf{y}}_{nj} = \mathbf{A} \mathbf{e}_{n} y_{nj}">

I believe it is known that the two methods are equivalent when the sources are uncorrelated (as you show above?).

**Comment by tky823** [comment]
So you mean that the implementation of "projection back" is different from what the name signifies, but in terms of the scale and phase restoration, it doesn't matter?

**Comment by fakufaku** [comment]
Yes, exactly. I mixed up the names of the algorithms when I first implemented this. 😓 
Both algorithms solve the same problem and will allow you to recover scale and phase. While equivalent under some assumptions in theory, the assumptions are violated in practice and you will obtain different results. I actually wrote a paper on this that describes both methods (and some new one), [here](https://arxiv.org/pdf/2009.05288.pdf). You may want to check the [code companion to this paper](https://github.com/fakufaku/2020_interspeech_gmdp) that contains correctly named methods for both algorithms.
Did you experience any problem with the `proj_back` in pyroomacoustics ?

**Comment by tky823** [comment]
I haven't experienced problems. Just I was wondering about the implementation.
Thanks for explaining.

**Comment by datalw** [comment]
> Yes, exactly. I mixed up the names of the algorithms when I first implemented this. 😓 Both algorithms solve the same problem and will allow you to recover scale and phase. While equivalent under some assumptions in theory, the assumptions are violated in practice and you will obtain different results. I actually wrote a paper on this that describes both methods (and some new one), [here](https://arxiv.org/pdf/2009.05288.pdf). You may want to check the [code companion to this paper](https://github.com/fakufaku/2020_interspeech_gmdp) that contains correctly named methods for both algorithms. Did you experience any problem with the `proj_back` in pyroomacoustics ?

Hi, 
I am new to IVA and auxIVA and have some questions about recovering the scale and phase. 
My motivation is that I need to eliminate some sources from the source signal and then reproduce the leftover observation signal.

Before I do the reverse step with a mixing matrix, I tried to use the demixing matrix directly from the result of the function `auxiva`:
When `proj_back=False`, the source signal from the result of the function is equal to einsum of the demixing matrix and the observation signal. In the case of `proj_back=True`, they are not equal, because they have different scales. 
Same scale:
![same_scale](https://github.com/LCAV/pyroomacoustics/assets/45690539/8d2d8e21-08e4-4502-955f-c43cffc3158c)
Different scale:
![different_scale](https://github.com/LCAV/pyroomacoustics/assets/45690539/8c4add04-da88-4400-a469-413494556866)

The code is as following:

```
import pyroomacoustics as pra
import numpy as np
import matplotlib.pyplot as plt

X_orig = np.load("test_signal_components.npy") #shape==(nframe, nfrequency, nchannel)
X = abs(X_orig) # take only the magnitude

# the two source signals have the same scale
S,demix = pra.bss.auxiva(X,n_src=10, n_iter=20,proj_back=False,model='laplace',init_eig=False,return_filters=True)
plt.plot(np.einsum('fqc,tfc->tfq',demix,X)[:,0,0], 'x-', label='demix $\cdot$ X') 
plt.plot(S[:,0,0],'--',label= 'S')
plt.legend()

# the two source signals have the different scales
S,demix = pra.bss.auxiva(X,n_src=10, n_iter=20,proj_back=True,model='laplace',init_eig=False,return_filters=True)

fig, ax = plt.subplots(2,1)
ax[0].plot(np.einsum('fqc,tfc->tfq',demix,X)[:,0,0], '--', label='demix $\cdot$ X') 
ax[1].plot(S[:,0,0],'--',label= 'S')
for i in ax:
    i.legend()

``` 

I would like to know 
(1) How can I recover the scale in the source signal?

(2) According to the documentation for the function `auxiva`, the input should be STFT representation of the observation signal. In my case, I have to use other decomposition methods than STFT and have negative values in the representation. When using `auxiva`, I had to use `abs(representation)` to get the magnitude as input, or else I got `RuntimeWarning: invalid value encountered in sqrt  W[:, s, :] /= np.sqrt(denom[:, :, 0])`. Does the representation input have to be positive?

(3) Last question is a bit general, since I am quite new to this method... Since my initial goal is to reproduce the leftover observation signal, is there a way to reproduce the original representation with negative values when doing mixing matrix $`\cdot`$ source signal? Let's say I have to set the first source to 0, because it has been identified as noise. Then I want to get the leftover representation of the observation signal without the first source (noise). 

Btw. In the documentation, it says the demix matrix has the shape of (nfrequencies, nchannels, nsources). The code gives (nfrequencies, nsources, nchannels) ;)

**Comment by datalw** [comment]
Here is the input data `test_signal_components.npy`: https://drive.google.com/file/d/1R3urWdceZCBnJHY4j0XpPL8NXVcl6Vu4/view?usp=sharing
