### ISSUE TITLE
Add speed of sound as a parameter

### ISSUE THREAD

**Issue by FrancoisGrondin** [LCAV/pyroomacoustics#23]
It would be interesting to be able to add the speed of sound as a parameter for the room. This value seems to be hardcoded to 343 m/sec, but it may change according to the temperature within the room, and one may want to play with this parameter.

Thanks!

**Comment by fakufaku** [comment]
Hi François, physical constants are currently set package wide. It is possible to change their values like this.

    import pyroomacoustics as pra
    pra.constants.set('c', 350)

You can also get the current value.

    c = pra.constants.get('c')
    print('The speed of sound is:', c)

Do you think there would be a need to set the speed of sound for individual rooms ?

**Comment by FrancoisGrondin** [comment]
Thank you for the precision! In this case I think this is sufficient :) The way I see it is that the room object holds all physical properties of the room (dimensions, absorption, etc.) and thus to my view it was logical to also include speed of sound as it depends on physical properties such as temperature, humidity and pressure. That being said, I feel this can be easily done with the method you just showed me.

Thanks!

**Comment by fakufaku** [comment]
Thanks for the input. It makes a lot of sense. I think the reason I originally did that is that several modules/objects need the parameter (Room, Beamformer, DOA, etc) and that rather than passing `c` around I have created a global variable.

That being said, the actual physical parameter and the value used in the processing algorithm does not need to be the same. It might actually need to be different when evaluating the impact of model mismatch for example. So I might get around to pushing `c` in room at some point.
