### ISSUE TITLE
Length of recorded signal

### ISSUE THREAD

**Issue by johanbn** [LCAV/pyroomacoustics#245]
Hi,

The length of the recorded signal and the one used in the simulation is not of the same length. Is there an explanation for it? Need to correct for it since the audio has annotations I would like to use.

**Comment by fakufaku** [comment]
Hi @johanbn , this is expected behavior. The simulation will create room impulse responses and convolve them with the input signal. If your signal has length `N` and the impulse response length `L`, then the convolution output has `L + N - 1` samples. Since you need to correct for audio annotations, you may also be interested to know that the simulation will add a 40 samples offset to start times.

If you want to inspect the impulse response to determine the length and start times, they are stored in `room.rir`. This is a list of lists with the first list over microphones, and the second over sources.

**Comment by johanbn** [comment]
Appreciate the answer! Removing the L/2 first and last samples then.
