### ISSUE TITLE
Question : GPU support?

### ISSUE THREAD

**Issue by pfeatherstone** [LCAV/pyroomacoustics#253]
Why was GPU support removed?
In the original repository CUPY was used instead of NUMPY. You could even set this as a runtime switch.
Seems silly to have removed this.
Or have I lost the plot and you do in fact support GPU?

**Comment by fakufaku** [comment]
Hi @pfeatherstone , I don't think we ever supported GPU... Maybe you are thinking of a different project ?

**Comment by pfeatherstone** [comment]
@sekiguchi92 originally wrote a repo called "SpeechEnhancement" that had all the NMNF, IRLMA stuff and it switched between CUPY and NUMPY. I was under the impression this repo was based on that.

**Comment by fakufaku** [comment]
Ah, you are referring to the source separation only. I remember seeing something like that in his repo indeed. It seems it was not carried over to the implementation in pyroomacoustics. @sekiguchi92 contributed the code so he is best placed to answer this I think. On the other hand, it should be pretty trivial to change the import statement to use cupy instead of numpy.

**Comment by pfeatherstone** [comment]
yeah and hopefully "it just works" :)

**Comment by sekiguchi92** [comment]
I'm sorry I changed the repo name to SoundSourceSeparation (https://github.com/sekiguchi92/SoundSourceSeparation).
Now I'm refactoring the code, and MNMF and ILRMA are not available for now. Please wait for a while.
