### ISSUE TITLE
trinicon test

### ISSUE THREAD

**Issue by snsun** [LCAV/pyroomacoustics#35]
Hi, 
Have you ever tested trinicon.py? I tried to use trinicon using my own data, but I got very strange output. 

Thanks

**Comment by fakufaku** [comment]
Hi @snsun , thanks for your report. Back when I coded this (a few years ago), it seemed to be (somewhat) working. I have to admit performance was not stellar. When I reorganized the `bss` code recently and added some new algorithm, I couldn't get it to work. This surely needs to be documented.

I have a test file that I created that can be used to assess the performance. I will create a new branch and add it there.

Would you be okay to share the kind of scenario you were trying to use it with ? (number of microphones, sources, types of signals, filter length, reverberation time, etc). Also, if you manage to find out why the algorithm doesn't work and would like to share this back, that would be great. I will also try to look into it. I'm a bit short on time these days, so progress might not be super fast. Thanks for your understanding.

**Comment by fakufaku** [comment]
So I took a quick look and added a working example of Trinicon in [`bss/tests/test_trinicon.py`](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/bss/tests/test_trinicon.py). I have also improved Trinicon API so that you can specify all the parameters of the algorithm.

The current example I have successfully separates two speakers using two microphones. First, I have used anechoic conditions were separation is guaranteed to be possible. Second, the algorithm needs to be run several times on the speech sample in order to get convergence of the filters. Third, the tuning of the parameters seems finicky. Fourth, it is important that the signals to separate be broadband (I had first used harmonic singing signal which could not be successfully be separated).

So it seems that the algorithm is working, but might be hard to tune. Also, be careful if using only two mics, some source placements do not allow separation (e.g. if the sources are placed symmetrically across the line formed by the two microphones).

Please let me know if that helps and if you find other problems. If not I'll close this.

**Comment by snsun** [comment]
Hi @fakufaku. Thanks for your thorough reply. My test data was recorded using 4-mic linear array (4cm) in an anechoic room.  There are two speakers. I just found that it cannot separate two speakers.  Now I am trying to understand the paper and your code. I will try your new test file. 

Thank you very much!

**Comment by fakufaku** [comment]
I see, thanks for the info. Recordings in anechoic room should work pretty well. It seems that the convergence of Trinicon is not so fast (maybe the parameters can be tuned), so you might need to make several pass on the data to obtain convergence. I do this in the example file. I provide the filters obtained at the previous step as the starting point of the next.
