### ISSUE TITLE
Question about the BSS eval in IVA script

### ISSUE THREAD

**Issue by ahikaml** [LCAV/pyroomacoustics#39]
Hi,
Thanks for this tool. Very impressive.
I saw that in "**bss_iva.py**" you used **bss_eval_images** in order to measure the preformances of the separation in terms of SIR, SDR, etc..
However it seems that you take into consideration only the first reference channel (the source after the RIR as it was received in the first mic).
Could it degrade the comparison? After all the estimated source is actually a convolutive combination of the signals from all mics, and the reference source is from one mic.

Thanks

**Comment by fakufaku** [comment]
Hi @ahikaml ,
Thanks for the question! And I'm happy you find this package useful.
To answer your question, when you do frequency domain source separation (or beamforming in some cases), there is an ambiguity whereas you could change arbitrarily the magnitude at every frequency without changing the optimality of your separation filters. One popular way to avoid this ambiguity (the one used in pyroomacoustics) is to *project back* the output from the beamformer onto one of the input channels. The function doing this is [`pyroomacoustics.bss.common.projection_back`](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.bss.common.html?highlight=bss). In words, this means that the average magnitude and phase delay of the output of the beamformer is changed to matched one of the input channels (the first usually). This means that the reverberation and delay of that microphone will be also matched to the output. Therefore it makes sense to compare the output to this microphone.
Now it is perfectly possible to do the back projection for every input channel (and thus produce a matching number of output channels), and compare all of them with `bss_eval`. This would make sense in the case where the reference microphone chosen only contains a very corrupted version of one of the sources.
If both sources are approximately of equal strength at that microphone, it should be ok to pick only this one for the evaluation.
At least I think! I'd be happy to hear any argument making the case for comparing all the channels. (Note that there is a computational cost to comparing all channels since `bss_eval_images` is not exactly light).

**Comment by ahikaml** [comment]
Thanks for the detailed answer!

> One popular way to avoid this ambiguity (the one used in pyroomacoustics) is to project back..

Could you please direct me to the reference?

> Therefore it makes sense to compare the output to this microphone

I'm using the IVA method from the reference below* which solves the scaling problem by adjusting the whole separating matrix using the "minimal distortion principle". Does it say that using the bss_eval_images only with the first mic is sufficient just for methods which solved the scaling problem using only the first mic?

*(T. Kim, H. T. Attias, S.-Y. Lee, and T.-W. Lee, “Blind source separation exploiting higher-order frequency dependencies,” IEEE Trans. Audio,
Speech and Language Processing, pp. 70–79, Jan. 2007)

**Comment by fakufaku** [comment]
The reference for projection back seems to be the following.

> N. Murata, S. Ikeda, and A. Ziehe, “An Approach to Blind Source Separation Based on Temporal Structure of Speech Signals,” Neurocomputing, vol. 41, no. 1, pp. 1–24, 2001.

After asking around, it seems that indeed `bss_eval_images` is more appropriate for the multichannel case. That is when the separated signal is projected back once on every microphone signal, and then all the microphones are evaluated simulataneously. In that case it is important to evaluate the spatial distortion introduced by the separation (the **ISR** metric). When only a single microphone is used, the `bss_eval_sources` (see in [mir_eval](https://github.com/craffel/mir_eval/blob/master/mir_eval/separation.py#L130)) is the appropriate solution. From the discussion I had, it wasn't clear that using `bss_eval_images` on a single microphone would result in wrong evaluation. It might only incur extra computation due to the ISR metric being computed. But I can't be completely sure.

Regardless, since it now appears that I should have been using `bss_eval_sources`, I will update my code.

**Comment by fakufaku** [comment]
Fixed in https://github.com/LCAV/pyroomacoustics/commit/49a28749c4cf6858777c70acec985bcde92dfed9
