### ISSUE TITLE
Adding datatype parameter to STFT class

### ISSUE THREAD

**Issue by jazcarretao** [LCAV/pyroomacoustics#82]
When using the new STFT object contained in `pyroomacoustics.stft` I ran into a precision issue that I could solved by manually casting (from complex64 to complex128) the output data type of the analysis and synthesis method.

Currently, `pyroomacoustics.stft` uses a datatype of 32 bits (float32/complex64). I propose adding another input parameter to the constructor in order to specify the bits width (32 bits or 64 bits). The default value would be 32. This is the same idea as the `bits` input that is already used in the `dft.py` constructor.

When fixing my particular issue, I started implementing this feature in this branch:
https://github.com/jazcarretao/pyroomacoustics/tree/juan-dev-stft

The main changes in `stft.py` can be found in this commit:
https://github.com/jazcarretao/pyroomacoustics/commit/7ba2dd2fe03205a82032d3c59ffa9a1a97f09c32

Thank you for your attention.

**Comment by fakufaku** [comment]
Hi @jazcarretao , very good catch. I think the strategy you propose is sound, but I would suggest a few differences.

1. The new parameter can be called `precision` and accept the following values:
    
    * `single`, `numpy.float32`, `numpy.complex64`
    * `double`, `numpy.float64`, numpy.complex128`
    
    This way, it is possible to infer the type needed directly from a given `numpy` array's `dtype` attribute.
2. Set the default to  `double` as this is what most people are probably expected and will lead to smallest discrepancy with previous implementation.
3. In `pra.transform.analysis` and `pra.transform.synthesis`, infer the type from the array provided.

If you want I can make the change, or you can make it on top of the current master and do a pull request.

**Comment by jazcarretao** [comment]
Thank you for the comments.
I can do it to complete my PR. We could call this parameter `dtype` instead of `precision`. This would resemble the `dtype` parameter used to create `numpy` arrays.

As well, if we do this change I believe we should modify `bits` input parameter in `dft.py` to keep consistency of the parameters across functions.

**Comment by fakufaku** [comment]
I have thought of using the `dtype` parameters. One problem though is that we will not accept all values (e.g., `np.int`, `np.int16`, will not be supported). Also, it should actually take pairs of types `(np.float32, np.complex64)` or `(np.float64, np.complex128)` because of the time/freq dual representation. This is why I thought the `precision` keyword might be more appropriate...

Good point about `dft.py`. I believe we should also change that one. I am not particularly worried about breaking the API there since probably very few people are using it anyway. Let's do it. If we are worried, we can keep it with a deprecation warning and remove it in the future.
