### ISSUE TITLE
Source directivity pattern and microphone pickup pattern

### ISSUE THREAD

**Issue by m-pexx** [LCAV/pyroomacoustics#85]
First **thank you** for your work in implementing this python package. I think that a nice feature would be to include the *directivity pattern* (radiance pattern) of the source in the impulse response generator. Additionally, also microphones could have a *pickup pattern*. Similar simulators, such as [RIR generator](https://github.com/ehabets/RIR-Generator)  and [SMIR generator](https://github.com/ehabets/SMIR-Generator) have these options.

**Comment by fakufaku** [comment]
Hi @m-pexx , thanks for the kind words and the suggestion. Indeed, this would be nice! I should really create a ROADMAP document so that it is public what are planned improvements.
We are currently working on adding new ways of simulating non-shoebox rooms with multi-band absorption and scattering characteristics. As part of these improvements are ways of tracking directional patterns of receivers (and somewhat sources). Thus, directional microphones should be supported at some point in the future (can't really give a timeline for now, but probably this year).

In case you are interested to pick this up and contribute something, please let me know!

**Comment by m-pexx** [comment]
@fakufaku I am glad to know that you are actively working. Implementing features like scattering, frequency dependent absorption would be really the key for shifting from MATLAB to python. I expect adding the radiance/pick-up pattern in the image-source method not being a big issue, considering also the validity of reciprocity principle in that context.

**Comment by xaviliz** [comment]
Count on me with future contributions. I have not so much time but I would like to contribute.
Thanks, XL

**Comment by fakufaku** [comment]
Basic source and directivity patterns have been recently implemented for the shoebox image source model! 🎉 Please have a look at the documentation.
